import { initializeApp } from 'firebase/app';
import { getMessaging, getToken, onMessage } from 'firebase/messaging';

const firebaseConfig = {
  apiKey: "AIzaSyBZEu71fxzgVsxnUDeJlR-FwRsQzBuwYEc",
  authDomain: "shopu-d287a.firebaseapp.com",
  projectId: "shopu-d287a",
  storageBucket: "shopu-d287a.firebasestorage.app",
  messagingSenderId: "874740883567",
  appId: "1:874740883567:web:28a352131794cdfc6aad9a"
};

const app = initializeApp(firebaseConfig);

export const messaging = typeof window !== 'undefined' ? getMessaging(app) : null;

export const requestFCMToken = async (userId: number, retryCount = 0): Promise<string | null> => {
  const MAX_RETRIES = 3;
  const RETRY_DELAY = 1000; // 1 second

  console.log(`[FCM] Starting FCM token request for user: ${userId} (attempt ${retryCount + 1})`);

  // Vérifier que l'userId est valide
  if (!userId || userId <= 0) {
    console.warn('[FCM] Invalid userId, skipping FCM token request');
    return null;
  }

  if (!messaging) {
    console.error('[FCM] Firebase messaging not available');
    return null;
  }

  try {
    // Vérifier si les notifications sont supportées
    if (!('Notification' in window)) {
      console.warn('[FCM] Notifications not supported in this browser');
      return null;
    }

    console.log('[FCM] Requesting notification permission...');
    const permission = await Notification.requestPermission();
    console.log(`[FCM] Permission result: ${permission}`);

    if (permission !== 'granted') {
      console.log('[FCM] Notification permission denied by user');
      return null;
    }

    console.log('[FCM] Getting FCM token with VAPID key...');
    const token = await getToken(messaging, {
      vapidKey: process.env.NEXT_PUBLIC_FCM_VAPID_KEY
    });

    if (!token) {
      console.warn('[FCM] No token generated by Firebase');
      return null;
    }

    console.log(`[FCM] Token generated successfully: ${token.substring(0, 20)}...`);

    // Register with backend avec retry
    let registrationSuccess = false;
    let lastError: any = null;

    for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
      try {
        console.log(`[FCM] Backend registration attempt ${attempt + 1} for user: ${userId}`);

        const response = await fetch('/api/devices/register', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            user_id: userId,
            device_token: token,
            platform: 'web'
          })
        });

        if (response.ok) {
          console.log(`✅ FCM token registered successfully for user: ${userId}`);
          registrationSuccess = true;
          break;
        } else {
          const errorText = await response.text();
          console.error(`❌ Backend registration failed (attempt ${attempt + 1}):`, response.status, errorText);
          lastError = new Error(`HTTP ${response.status}: ${errorText}`);

          // Attendre avant retry
          if (attempt < MAX_RETRIES - 1) {
            await new Promise(resolve => setTimeout(resolve, RETRY_DELAY));
          }
        }
      } catch (fetchError) {
        console.error(`❌ Network error during registration (attempt ${attempt + 1}):`, fetchError);
        lastError = fetchError;

        // Attendre avant retry
        if (attempt < MAX_RETRIES - 1) {
          await new Promise(resolve => setTimeout(resolve, RETRY_DELAY));
        }
      }
    }

    if (!registrationSuccess) {
      console.error(`💥 Failed to register FCM token after ${MAX_RETRIES} attempts:`, lastError);
      throw lastError;
    }

    return token;

  } catch (error) {
    console.error(`💥 Error getting FCM token for user ${userId}:`, error);

    // Retry logic pour les erreurs temporaires
    if (retryCount < MAX_RETRIES - 1) {
      console.log(`🔄 Retrying FCM token request in ${RETRY_DELAY}ms...`);
      await new Promise(resolve => setTimeout(resolve, RETRY_DELAY));
      return requestFCMToken(userId, retryCount + 1);
    }

    console.error(`💥 Max retries exceeded for user ${userId}`);
    return null;
  }
};

// Handle foreground messages
export const onMessageListener = () =>
  new Promise((resolve) => {
    if (messaging) {
      onMessage(messaging, (payload) => {
        console.log('Message received:', payload);
        resolve(payload);
      });
    }
  });